# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/sample-proto3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tests/sample-proto3.proto',
  package='tests.proto3',
  syntax='proto3',
  serialized_pb=_b('\n\x19tests/sample-proto3.proto\x12\x0ctests.proto3\"w\n\x0bSomeMessage\x12\x38\n\x08some_map\x18\x01 \x03(\x0b\x32&.tests.proto3.SomeMessage.SomeMapEntry\x1a.\n\x0cSomeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SOMEMESSAGE_SOMEMAPENTRY = _descriptor.Descriptor(
  name='SomeMapEntry',
  full_name='tests.proto3.SomeMessage.SomeMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tests.proto3.SomeMessage.SomeMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tests.proto3.SomeMessage.SomeMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=162,
)

_SOMEMESSAGE = _descriptor.Descriptor(
  name='SomeMessage',
  full_name='tests.proto3.SomeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_map', full_name='tests.proto3.SomeMessage.some_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SOMEMESSAGE_SOMEMAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=162,
)

_SOMEMESSAGE_SOMEMAPENTRY.containing_type = _SOMEMESSAGE
_SOMEMESSAGE.fields_by_name['some_map'].message_type = _SOMEMESSAGE_SOMEMAPENTRY
DESCRIPTOR.message_types_by_name['SomeMessage'] = _SOMEMESSAGE

SomeMessage = _reflection.GeneratedProtocolMessageType('SomeMessage', (_message.Message,), dict(

  SomeMapEntry = _reflection.GeneratedProtocolMessageType('SomeMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _SOMEMESSAGE_SOMEMAPENTRY,
    __module__ = 'tests.sample_proto3_pb2'
    # @@protoc_insertion_point(class_scope:tests.proto3.SomeMessage.SomeMapEntry)
    ))
  ,
  DESCRIPTOR = _SOMEMESSAGE,
  __module__ = 'tests.sample_proto3_pb2'
  # @@protoc_insertion_point(class_scope:tests.proto3.SomeMessage)
  ))
_sym_db.RegisterMessage(SomeMessage)
_sym_db.RegisterMessage(SomeMessage.SomeMapEntry)


_SOMEMESSAGE_SOMEMAPENTRY.has_options = True
_SOMEMESSAGE_SOMEMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
