# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/sample-proto3.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tests/sample-proto3.proto',
  package='tests.proto3',
  syntax='proto3',
  serialized_pb=b'\n\x19tests/sample-proto3.proto\x12\x0ctests.proto3\"\xb7\x01\n\x0bSomeMessage\x12\x38\n\x08some_map\x18\x01 \x03(\x0b\x32&.tests.proto3.SomeMessage.SomeMapEntry\x12*\n\nenum_field\x18\x02 \x01(\x0e\x32\x16.tests.proto3.SomeEnum\x12\x12\n\nbool_field\x18\x03 \x01(\x08\x1a.\n\x0cSomeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*%\n\x08SomeEnum\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0c\n\x08OPTION_1\x10\x01\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SOMEENUM = _descriptor.EnumDescriptor(
  name='SomeEnum',
  full_name='tests.proto3.SomeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPTION_1', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=229,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_SOMEENUM)

SomeEnum = enum_type_wrapper.EnumTypeWrapper(_SOMEENUM)
DEFAULT = 0
OPTION_1 = 1



_SOMEMESSAGE_SOMEMAPENTRY = _descriptor.Descriptor(
  name='SomeMapEntry',
  full_name='tests.proto3.SomeMessage.SomeMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tests.proto3.SomeMessage.SomeMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tests.proto3.SomeMessage.SomeMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=227,
)

_SOMEMESSAGE = _descriptor.Descriptor(
  name='SomeMessage',
  full_name='tests.proto3.SomeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_map', full_name='tests.proto3.SomeMessage.some_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enum_field', full_name='tests.proto3.SomeMessage.enum_field', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_field', full_name='tests.proto3.SomeMessage.bool_field', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SOMEMESSAGE_SOMEMAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=227,
)

_SOMEMESSAGE_SOMEMAPENTRY.containing_type = _SOMEMESSAGE
_SOMEMESSAGE.fields_by_name['some_map'].message_type = _SOMEMESSAGE_SOMEMAPENTRY
_SOMEMESSAGE.fields_by_name['enum_field'].enum_type = _SOMEENUM
DESCRIPTOR.message_types_by_name['SomeMessage'] = _SOMEMESSAGE
DESCRIPTOR.enum_types_by_name['SomeEnum'] = _SOMEENUM

SomeMessage = _reflection.GeneratedProtocolMessageType('SomeMessage', (_message.Message,), dict(

  SomeMapEntry = _reflection.GeneratedProtocolMessageType('SomeMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _SOMEMESSAGE_SOMEMAPENTRY,
    __module__ = 'tests.sample_proto3_pb2'
    # @@protoc_insertion_point(class_scope:tests.proto3.SomeMessage.SomeMapEntry)
    ))
  ,
  DESCRIPTOR = _SOMEMESSAGE,
  __module__ = 'tests.sample_proto3_pb2'
  # @@protoc_insertion_point(class_scope:tests.proto3.SomeMessage)
  ))
_sym_db.RegisterMessage(SomeMessage)
_sym_db.RegisterMessage(SomeMessage.SomeMapEntry)


_SOMEMESSAGE_SOMEMAPENTRY.has_options = True
_SOMEMESSAGE_SOMEMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001')
# @@protoc_insertion_point(module_scope)
